### ISSUE TITLE
Strange computations

### ISSUE THREAD

**Issue by dcoeurjo** [poncateam/poncascope#12]
After a clean build, when I use the armadillo asset and just click on the APSS and ASO without changing the parameters (same as in the video), I get some NaNs and plenty of `Warning: fit 7456 is not stable` messages.
Is that normal ? 

![Capture d’écran 2023-11-22 à 14 46 19](https://github.com/poncateam/poncascope/assets/700165/57bc8e14-f80e-4caa-becd-5bcb2fc67695)

**Comment by dcoeurjo** [comment]
(System: macOS, M1, default clang compiler)

**Comment by dcoeurjo** [comment]
Command line:
  
       poncascope assets/armadillo.obj

**Comment by ThibaultLejemble** [comment]
I found the error: https://github.com/poncateam/poncascope/blob/bbbbe66c8943aab7e1784a4827388d270a0c1f63/src/main.cpp#L56C36-L56C36
The range neighbor search is always done from the same point at index `iVertexSource` which I believe corresponds to the clicked point. 
I'll propose a fix.
